CREATE TABLE `car2` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`지역2` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`차충전기1` INT(10) NULL DEFAULT NULL,
	`차충전기2` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=34
;
