CREATE TABLE `car` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`지역1` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`등록대수1` INT(10) NULL DEFAULT NULL,
	`등록대수2` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;
