CREATE TABLE `car3` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`사업자` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`로밍평균요금` INT(10) NULL DEFAULT NULL,
	`회원평균요금` FLOAT NULL DEFAULT NULL,
	`비회원평균요금` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=31
;
